version: '2'

services:
  data-gathering:
    image: autocomplete-data-gathering:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./apps/data-gathering/Dockerfile
    container_name: data-gathering
    env_file:
      - ./apps/data-gathering/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  query:
    image: autocomplete-query:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./apps/query/Dockerfile
    container_name: query
    env_file:
      - ./apps/query/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3000'
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
